#!/bin/sh
#
# Starts Treadmill network management service
# Runs as root.
#

exec \
    {{ treadmill_bin }} \
    sproc --cgroup . \
    service \
        --root-dir {{ dir }} \
    presence \
        --zkid zkid.pickle
